CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Category" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Category" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240323184028_AddCategoryTable', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "User" (
    "Uuid" uuid NOT NULL,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Uuid")
);

CREATE TABLE "Transaction" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "CategoryId" integer NOT NULL,
    "SubcategoryId" integer,
    "Value" numeric NOT NULL,
    "Description" text,
    "TransactionType" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "ChangedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Transaction" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transaction_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Uuid") ON DELETE CASCADE
);

CREATE INDEX "IX_Transaction_UserId" ON "Transaction" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240323205706_AddUserTable', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Transaction" DROP CONSTRAINT "FK_Transaction_User_UserId";

ALTER TABLE "Category" ALTER COLUMN "Description" TYPE character varying(30);

CREATE TABLE "Subcategory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(100) NOT NULL,
    "CategoryId" integer NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_Subcategory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subcategory_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Subcategory_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Uuid") ON DELETE CASCADE
);

CREATE INDEX "IX_Subcategory_CategoryId" ON "Subcategory" ("CategoryId");

CREATE INDEX "IX_Subcategory_UserId" ON "Subcategory" ("UserId");

ALTER TABLE "Transaction" ADD CONSTRAINT "FK_Transaction_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Uuid") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240323205808_AddSubcategoryTable', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE INDEX "IX_Transaction_CategoryId" ON "Transaction" ("CategoryId");

CREATE INDEX "IX_Transaction_SubcategoryId" ON "Transaction" ("SubcategoryId");

ALTER TABLE "Transaction" ADD CONSTRAINT "FK_Transaction_Category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Category" ("Id") ON DELETE CASCADE;

ALTER TABLE "Transaction" ADD CONSTRAINT "FK_Transaction_Subcategory_SubcategoryId" FOREIGN KEY ("SubcategoryId") REFERENCES "Subcategory" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240324013513_AddCategoryAndSubcategoryRelationToTransaction', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Subcategory" ALTER COLUMN "UserId" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240324014436_AddUserIdAsNullable', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Transaction" ADD "WalletId" uuid;

CREATE TABLE "Wallet" (
    "Id" uuid NOT NULL,
    "Balance" numeric NOT NULL,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_Wallet" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Wallet_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Uuid") ON DELETE RESTRICT
);

CREATE INDEX "IX_Transaction_WalletId" ON "Transaction" ("WalletId");

CREATE INDEX "IX_Wallet_UserId" ON "Wallet" ("UserId");

ALTER TABLE "Transaction" ADD CONSTRAINT "FK_Transaction_Wallet_WalletId" FOREIGN KEY ("WalletId") REFERENCES "Wallet" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240330203922_CreateWalletTable', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Wallet" ADD "Description" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240331031016_AddDescriptionColumnAtWalletTable', '8.0.0');

COMMIT;

